
const ADD_STUDENT = "ADD_STUDENT";
const UPDATE_STUDENT = "UPDATE_STUDENT";
const DELETE_STUDENT = "DELETE_STUDENT";
const SET_CURRENT_UPDATE_STUDENT = "SET_CURRENT_UPDATE_STUDENT";
const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
const SET_CURRENT_COURSE_DETAIL = "SET_CURRENT_COURSE_DETAIL";

const FETCH_COURSES_ENROLLED = "FETCH_COURSES_ENROLLED";
const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";

const FETCH_STUDENT = "FETCH_STUDENT";
const FETCH_STUDENT_BY_ID = "FETCH_STUDENT_BY_ID";
const FETCH_STUDENT_BY_NAME = "FETCH_STUDENT_BY_NAME";
const FETCH_STUDENT_FROM_COURSE = "FETCH_STUDENT_FROM_COURSE";

const studentType = {
    ADD_STUDENT,
    DELETE_STUDENT,
    UPDATE_STUDENT,
    SET_CURRENT_UPDATE_STUDENT,
    SET_CURRENT_STUDENT,


    FETCH_STUDENT,
    FETCH_STUDENT_BY_ID,
    FETCH_STUDENT_BY_NAME,
    FETCH_STUDENT_FROM_COURSE,

    FETCH_COURSES_ENROLLED,
    FETCH_ALL_COURSES,

    SET_CURRENT_COURSE_DETAIL
}

export default studentType;