const GET_ALL_STUDENT = "GET_ALL_STUDENT";
const GET_STUDENT_ID = "GET_STUDENT_ID";
const GET_STUDENT_FULLNAME = "GET_STUDENT_FULLNAME";
const ADD_STUDENT = "ADD_STUDENT";
const UPDATE_STUDENT = "UPDATE_STUDENT";
const DELETE_STUDENT = "DELETE_STUDENT";
const SET_CURRENT_UPDATE_STUDENT = "SET_CURRENT_UPDATE_STUDENT";


const FETCH_STUDENT = "FETCH_STUDENT";


const studentType = {
    GET_ALL_STUDENT,
    GET_STUDENT_ID,
    GET_STUDENT_FULLNAME,
    ADD_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,

    SET_CURRENT_UPDATE_STUDENT,


    FETCH_STUDENT,
}

export default studentType;