const FETCH_ENROLLMENT = "FETCH_ENROLLMENT";
const FETCH_ENROLLMENT_BY_ID = "FETCH_ENROLLMENT_BY_ID";
const FETCH_ENROLLMENT_BY_STUDENT_ID = "FETCH_ENROLLMENT_BY_STUDENT_ID";
const FETCH_ENROLLMENT_BY_COURSE_ID = "FETCH_ENROLLMENT_BY_COURSE_ID";

const updateEnrollment = "UPDATE_ENROLLMENT";

const addEnrollment = "ADD_ENROLLMENT";
const deleteEnrollment = "DELETE_ENROLLMENT";

